### ISSUE TITLE
styleSheet.getName is not a function

### ISSUE THREAD

**Issue by ghost** [jxnblk/hidden-styled#5]
```
styleSheet.getName is not a function
TypeError: styleSheet.getName is not a function
    at ComponentStyle.generateAndInjectStyles (/www/node_modules/hidden-styled/node_modules/styled-components/lib/models/ComponentStyle.js:95:37)
    at StyledComponent.generateAndInjectStyles (/www/node_modules/hidden-styled/node_modules/styled-components/lib/models/StyledComponent.js:154:40)
    at StyledComponent.componentWillMount (/www/node_modules/hidden-styled/node_modules/styled-components/lib/models/StyledComponent.js:192:40)
    at resolve (/www/node_modules/react-dom/cjs/react-dom-server.node.development.js:2119:12)
    at ReactDOMServerRenderer.render (/www/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/www/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/www/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at renderPage (/www/node_modules/next/dist/server/render.js:176:26)
    at Function.renderPage [as getInitialProps] (/www/pages/_document.js:8:18)
    at _callee$ (/www/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/www/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/www/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/www/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/www/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /www/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
```

**Comment by ghost** [comment]
```
/www
├─┬ hidden-styled@1.0.0-0
│ └── styled-components@2.4.0
└─┬ rebass@2.0.0-0
  ├─┬ grid-styled@3.2.1
  │ └── styled-components@3.2.3  deduped
  ├── styled-components@3.2.3
  └─┬ system-components@2.0.2
    └── styled-components@3.2.3  deduped
```

**Comment by RoMay** [comment]
Make sure to use the same version of styled components.

**Comment by ghost** [comment]
Yep I got it. Thanks for the feedback!
